name: documentation

on:
  pull_request:
    branches: [latest]
  push:
    branches: [latest]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Lint
        run: |
          npm ci
          npm run textlint
      - name: Test Build
        run: |
          cd website
          npm ci
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Release to GitHub Pages
        run: |
          git config --global user.email "christopher.astfalk@icloud.com"
          git config --global user.name "Christopher Astfalk"
          echo "machine github.com login ${{ secrets.GH_NAME }} password ${{ secrets.GH_TOKEN }}" > ~/.netrc
          cd website && npm ci && GIT_USER="${{ secrets.GH_NAME }}" npm run publish-gh-pages
